name: CI

on:
  push:
    branches:
      - feature/DeBoostify
  pull_request:
    branches:
      - feature/DeBoostify

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2
      with:
        cmake-version: '3.25'

    - name: Set up dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Set up dependencies
      if: runner.os == 'macOS'
      #run: brew install cmake

    #- name: Set up dependencies
      #if: runner.os == 'Windows'
      #run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S $GITHUB_WORKSPACE -B build -DSpecUtils_BUILD_UNIT_TESTS=ON -DSpecUtils_BUILD_REGRESSION_TEST=ON -DSpecUtils_ENABLE_EQUALITY_CHECKS=ON -DPERFORM_DEVELOPER_CHECKS=OFF -DSpecUtils_ENABLE_D3_CHART=ON -DSpecUtils_D3_SUPPORT_FILE_STATIC=ON -DSpecUtils_ENABLE_URI_SPECTRA=OFF 

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --test-dir build -C Release
